################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
driverslib/msp432/adc14.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/adc14.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/aes256.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/aes256.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/comp_e.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/comp_e.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/cpu.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/cpu.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/crc32.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/crc32.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/cs.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/cs.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/dma.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/dma.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/flash.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/flash.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/fpu.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/fpu.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/gpio.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/gpio.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/i2c.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/i2c.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/interrupt.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/interrupt.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/mpu.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/mpu.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/pcm.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/pcm.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/pmap.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/pmap.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/pss.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/pss.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/ref_a.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/ref_a.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/reset.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/reset.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/rtc_c.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/rtc_c.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/spi.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/spi.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/sysctl.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/sysctl.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/systick.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/systick.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/timer32.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/timer32.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/timer_a.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/timer_a.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/uart.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/uart.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/wdt_a.obj: /Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432/wdt_a.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Applications/ti/ccsv8/ccs_base/arm/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/freertos/cortex-m4" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/msp432" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/board" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/oslib" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/include" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cc3100/simplelink/source" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/cmsis" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/inc" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_cc3100_boosterpack" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/driverslib/ti_msp432_launchpad" --include_path="/Users/randa/Desktop/SistemesEncastats/FreeRTOS_PingPong/05-mutex" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.3.LTS/include" --include_path="/Applications/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/$(basename $(<F)).d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


