################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
driverslib/cc3100/simplelink/source/device.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/cc3100/simplelink/source/device.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01b-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/cc3100/simplelink/source/device.d_raw" --obj_directory="driverslib/cc3100/simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/cc3100/simplelink/source/driver.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/cc3100/simplelink/source/driver.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01b-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/cc3100/simplelink/source/driver.d_raw" --obj_directory="driverslib/cc3100/simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/cc3100/simplelink/source/flowcont.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/cc3100/simplelink/source/flowcont.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01b-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/cc3100/simplelink/source/flowcont.d_raw" --obj_directory="driverslib/cc3100/simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/cc3100/simplelink/source/fs.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/cc3100/simplelink/source/fs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01b-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/cc3100/simplelink/source/fs.d_raw" --obj_directory="driverslib/cc3100/simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/cc3100/simplelink/source/netapp.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/cc3100/simplelink/source/netapp.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01b-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/cc3100/simplelink/source/netapp.d_raw" --obj_directory="driverslib/cc3100/simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/cc3100/simplelink/source/netcfg.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/cc3100/simplelink/source/netcfg.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01b-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/cc3100/simplelink/source/netcfg.d_raw" --obj_directory="driverslib/cc3100/simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/cc3100/simplelink/source/socket.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/cc3100/simplelink/source/socket.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01b-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/cc3100/simplelink/source/socket.d_raw" --obj_directory="driverslib/cc3100/simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/cc3100/simplelink/source/spawn.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/cc3100/simplelink/source/spawn.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01b-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/cc3100/simplelink/source/spawn.d_raw" --obj_directory="driverslib/cc3100/simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/cc3100/simplelink/source/wlan.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/cc3100/simplelink/source/wlan.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01b-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/cc3100/simplelink/source/wlan.d_raw" --obj_directory="driverslib/cc3100/simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


