################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
driverslib/msp432/adc14.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/adc14.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/adc14.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/aes256.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/aes256.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/aes256.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/comp_e.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/comp_e.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/comp_e.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/cpu.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/cpu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/cpu.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/crc32.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/crc32.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/crc32.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/cs.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/cs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/cs.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/dma.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/dma.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/dma.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/flash.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/flash.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/flash.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/fpu.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/fpu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/fpu.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/gpio.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/gpio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/gpio.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/i2c.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/i2c.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/i2c.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/interrupt.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/interrupt.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/interrupt.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/mpu.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/mpu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/mpu.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/pcm.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/pcm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/pcm.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/pmap.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/pmap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/pmap.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/pss.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/pss.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/pss.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/ref_a.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/ref_a.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/ref_a.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/reset.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/reset.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/reset.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/rtc_c.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/rtc_c.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/rtc_c.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/spi.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/spi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/spi.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/sysctl.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/sysctl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/sysctl.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/systick.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/systick.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/systick.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/timer32.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/timer32.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/timer32.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/timer_a.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/timer_a.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/timer_a.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/uart.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/uart.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/uart.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driverslib/msp432/wdt_a.obj: C:/Users/Pere\ Tuset/Desktop/Bitbucket/UOC/Sistemas\ Embebidos/2018_pac2/driverslib/msp432/wdt_a.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/source" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_msp432_launchpad" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/freertos/cortex-m4" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cmsis" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/inc" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/msp432" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/board" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/oslib" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/cc3100/simplelink/include" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/driverslib/ti_cc3100_boosterpack" --include_path="C:/Users/Pere Tuset/Desktop/Bitbucket/UOC/Sistemas Embebidos/2018_pac2/01a-task" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --advice:power="all" --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driverslib/msp432/wdt_a.d_raw" --obj_directory="driverslib/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


